name: cypress-ci

on:
  pull_request:
    branches:
      - 'main'
      - 'feature/upgrade-cypress'

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Instala as dependências, cria configs e executa testes
        run: cd src/ && npm install && npx cypress run --spec "cypress/e2e/agentesPage/*.js"

      - name: Cypress Screenshots
        uses: actions/upload-artifact@v4
        if: failure()
        with:
            name: cypress-screenshots
            path: src/cypress/screenshots
            if-no-files-found: ignore